Use filter to limit to branch

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -103,18 +103,29 @@ jobs:
     <<: *defaults
     steps:
       - checkout
-      - run: sudo apt-get -y -qq install awscli
-      - run: sudo npm install -g jsdoc
+      - run:
+          name: Install AWS CLI
+          command: sudo apt-get -y -qq install awscli
+      - run:
+          name: NPM Install JSDoc
+          command: sudo npm install -g jsdoc
       - run:
           name: Build JSDoc files
-          command: jsdoc . \
-            --verbose \
-            --configure .reaction/jsdoc/jsdoc.json \
-            --readme .reaction/jsdoc/templates/static/README.md
+          command: |
+            jsdoc .
+              --verbose \
+              --configure .reaction/jsdoc/jsdoc.json \
+              --readme .reaction/jsdoc/templates/static/README.md
       - run:
           name: Deploy Doc files to S3 if on Master
           command: |
-            echo "deploy...."
+            if [[ "${API_DOC_BUCKET}" && "${API_DOC_BUCKET_REGION}" ]]; then
+              echo "Deploying..."
+            else
+              echo "S3 bucket configuration not found for jsdocs"
+              echo "Set API_DOC_BUCKET and API_DOC_BUCKET_REGION to build and deploy jsdocs to S3"
+              exit 1;
+            fi
 
   eslint:
     <<: *defaults
@@ -156,3 +167,6 @@ workflows:
   build_and_test:
     jobs:
       - deploy-docs
+          filters:
+            branches:
+              only: /^master$/
